name: Manual Practice

on:
  workflow_dispatch:

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "I started this workflow manually"

      - name: Step 2
        run: echo "I am learning GitHub Actions"
